services:
  apache:
    build: ./docker/apache/
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - public

  php:
    build: ./docker/php/
    volumes: 
      - ./app/:/var/www/html/
    ports:
      - 9000:9000
    depends_on: 
      - mysql
    networks:
      - public
      - private

  mysql:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - private

networks:
  public:
  private:

volumes:
  db: